# Generated by Django 3.1.7 on 2021-04-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U2H', '0003_cleanliness'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.TextField(default='Student'),
        ),
    ]
